### ISSUE TITLE
Doesn't run on windows

### ISSUE THREAD

**Issue by AndersNS** [react-toolbox/react-toolbox-example#1]
Seems to be related to this issue: https://github.com/webpack/webpack-dev-server/issues/155

Running `npm start` just results in the message `webpack: wait until bundle finished` and an unresponsive localhost:8080.

**Comment by javivelasco** [comment]
Considering you already investigated the issue, do you know if we can do something to fix it in toolbox project? Or should it be fixed at webpack?

**Comment by AndersNS** [comment]
I have similar projects that work with webpack so it should be possible to fix in the toolbox project. The material-ui webpack sample works fine. :)

**Comment by jonasem** [comment]
Check out line 19 in webpack config

```
resolve: {
    extensions: ['', '.jsx', '.scss', '.js', '.json'],
     modulesDirectories: [
      './node_modules',
      path.resolve(__dirname, './node_modules')
    ]
  },
```

The '' entry certainly makes my webpack stoic. Removing it makes webpack start bundling at least.

**Comment by AndersNS** [comment]
If I change the start command to this `"start": "set UV_THREADPOOL_SIZE=100 & node ./server",` it works on Windows for me. I see there is `process.env.UV_THREADPOOL_SIZE = 100;` at the top of server.js but that doens't work for Windows then I assume?

**Comment by javivelasco** [comment]
I think so @AndersNS. The `UV_THREADPOOL_SIZE` is necessary because to keep the project modular we need a lot of SASS files to be compiled. There is a issue in `node_sass` that stops compiling if the threadpool is not incremented.

I guess that maybe is not possible to keep a working configuration for both OS? 
Thanks both of you guys! :)

**Comment by AndersNS** [comment]
I got it working in a different project properly earlier today. So I did some more investigation, because the webpack configs were very similar. What I found is it works for me If I remove the `process.env.UV_THREADPOOL_SIZE = 100;` from line 1 in server.js. If *NIX machines needs this to be set at something larger than the default (4) then keeping it working on both *NIX and Windows might be difficult.

**Comment by javivelasco** [comment]
+1

**Comment by javivelasco** [comment]
I mean... this setting shouldn't depend on your system. I would like somebody to send a PR with a working approach for windows and still working on UNIX machines. But! the setting should be implicit for now so people wouldn't have any problems running the project.

**Comment by ghost** [comment]
Fixed with [cross-env](github.com/kentcdodds/cross-env)
