### ISSUE TITLE
Hot module reloading not working

### ISSUE THREAD

**Issue by wKich** [react-toolbox/react-toolbox-example#13]
<img width="515" alt="screen shot 2015-11-26 at 12 37 29" src="https://cloud.githubusercontent.com/assets/6397708/11417645/80adf8aa-943a-11e5-804a-f13c329364dc.png">

**Comment by javivelasco** [comment]
We've updated the configuration to Babel 6 but there is  still no support in HMR. When they have it working we can update or we can just drop Babel 6 and return to the previous version to support HMR in the example

**Comment by justingreenberg** [comment]
fyi eslint is also not supported

**Comment by javivelasco** [comment]
Ok thanks!

I don't know if there are any interest about using the example as a boilerplate instead of just an example of integration. To use as a boilerplate with HMR we have to get rid of Babel 6 since it's not yet supported.

**Comment by delaneyj** [comment]
React transformer now works with babel 6 in it's 2.x branch

**Comment by javivelasco** [comment]
Yeah, we need to update the example. Hope to have time next week! 
Thanks for commenting it!

**Comment by nutrina** [comment]
Hello

I have run into the same problem right now.
Has this issue been fixed already? Or can somebody please provide a hint?

Thanks.

**Comment by dxps** [comment]
@nutrina While trying to help, I manage to have a [working setup with HMR](https://github.com/visvadw/react-redux-toolbox-starter). I hope it helps for now.
It should be a good starter, currently with a dev config only. A prod config will soon be added.

@javivelasco Javi, what do you think?
I know, it's still a work in progress, as my learning on react-toolbox, webpack and many other goodies in the JS world. :-)

**Comment by davidascher** [comment]
@visvadw thanks for that, it'll be useful to me at least.  I love HMR, react-toolbox looks awesome, and was disappointed to find that the current state is borked.

**Comment by nutrina** [comment]
@visvadw: Thanks :). It's working for me.
Would it also be possible to use HMR for the CSS files?

**Comment by dxps** [comment]
@nutrina Glad that I could help. I found an workaround for HMR-ing CSS files too.
- It looks like that `ExtractTextPlugin` does not work with HMR, so I remove it:

```
{
   test: /(\.scss|\.css)$/,
   // ExtractTextPlugin does not work with HMR, but it will be included in webpack prod config
   // loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap!toolbox')
   loader: 'style!css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap!toolbox?sourceMap'
}
```
- Having this, assets/react-toolbox.css is not delivered (reference to it returned 404). Therefore I made an empty file `assets/react-toolbox.css` as didn't want to have any errors in the console.

And playing around I can confirm that changes in both `app/toolbox-theme.scss` and `app/style.scss` are hot reloaded. [This starter](https://github.com/visvadw/react-redux-toolbox-starter) was updated to include these changes.

**Comment by javivelasco** [comment]
Sorry for my late response guys! HMR is not working with `ExtractTextPlugin` so if you want you can configure webpack without it for development. The only problem I've found is that if you don't use `ExtractText` you may experience a small delay applying styles. This may affect to some components that need to check its own position on the screen and mounting time because the size can differ with and without styles.

Just try and check if it fits for your use case, but if components like the `IconMenu` don't work, that would be the reason

**Comment by carloscuatin** [comment]
use react-hot-loader in beta2 👍
