### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by amihaylov** [react-toolbox/react-toolbox-example#15]
Hi guys, I found react toolbox quite interesting so I decided to give it a try. Unfortunately I'm unable to start it. Tried node version 4.2.3 and 5.3.0 but both are stuck on npm start (npm run build is fine, deploy gives error). I'm attaching the log so you can have a look at it.
[npm-debug.txt](https://github.com/react-toolbox/react-toolbox-example/files/72808/npm-debug.txt)

**Comment by amihaylov** [comment]
Hmm after reinstalling node 5.3.0 and rerunning npm install and build all is running ok.

**Comment by javivelasco** [comment]
Great, thanks for the update!
