### ISSUE TITLE
Webpack hot module replacement

### ISSUE THREAD

**Issue by mauron85** [react-toolbox/react-toolbox-example#2]
First of all, thank you for this example. I struggled making react-toolbox work.

Is it possible to add webpack hot module replacement or another kind of auto app refresh on code change?

**Comment by javivelasco** [comment]
Of course, but I don't know if it's going to be possible for SASS changes. I have to look deeper at it but in the main repo I have HMR running for the `docs` subproject but not for the CSS. PR welcome here :)

**Comment by mauron85** [comment]
For beginning js reload would be enough for me ;-). Yes, I'll definitely want to contibute, but need to get more familiar with webpack ...

**Comment by javivelasco** [comment]
Great! We just released and still we need a lot of stuff to fix. 
Thanks for your contribution!
