### ISSUE TITLE
Minor correction needed to make it work on Windows

### ISSUE THREAD

**Issue by dyarkovoy** [react-toolbox/react-toolbox-example#22]
webpack.config.js, module.exports.sassLoader.data injects @import with backslash-delimited path on Windows. Backslashes are interpreted as escape characters by sass loader, so the path gets corrupted and loader fails. 
We need to either remove path.resolve here making sure that backslashes don't appear in the path, or replace backslashes with regular slashes after path.resolve (better alternative), or duplicate backslashes (perhaps even better one)

**Comment by javivelasco** [comment]
Yeah, this issue was mentioned in the main project. https://github.com/react-toolbox/react-toolbox/issues/561 here is a posted solution. Feel free to PR a correction if it can work for every system and thanks for reporting :)!

**Comment by EnzoMartin** [comment]
Might want to close this issue and maybe give this repo a cleanup of old issues and PRs :wink:
