### ISSUE TITLE
Remove stage-0 from required presets

### ISSUE THREAD

**Issue by treecoder** [react-toolbox/react-toolbox-example#24]
This boilerplate depends on `babel-preset-stage-0` -- which essentially means that projects that start off of this template will have to depend on ECMAScript features that have [gained no acceptance](https://tc39.github.io/process-document/).

**No project should have a stage-0 dependency.**

Hence pl;ease remove it from `package.json`.

**Comment by Kikobeats** [comment]
Can you convert this into a PR?

**Comment by javivelasco** [comment]
I'm ok with it :) as long as we include by default features like property initializers. I think they solve elegantly an important issue in React. Anyway they are stage-2 if I'm not wrong, and I think we are using nothing from s0

**Comment by treecoder** [comment]
I don't think it is a good idea to use anything that is not yet stage-4. Especially when a library is intended to be used by many. This same issue exists also with `react-toolbox` -- not just the example project, and we should remove `stage-X (x < 4)` from both projects, and should only depend on ES features that are sure to make it to the standard.

**Comment by javivelasco** [comment]
Well, there are some features that are really useful and are nothing but easy transformations that should cause no pain in users projects. The only feature from early stage that I'd miss is property initializers. Honestly I wouldn't get rid of it. Abusing ES7 features may be bad but I this case it's a good price to pay IMO

**Comment by treecoder** [comment]
`Object.observe` is an example. It was `stage-2`, and now a deprecated feature. Hence it is important to never rely on anything other than stage 4, no matter how promising it seems. Or else technical debt.

https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html

**Comment by msaron** [comment]
I cannot even install this example on Windows 10. Lots of errors.
