### ISSUE TITLE
ModuleNotFoundError on ~normalize.css

### ISSUE THREAD

**Issue by haskellcamargo** [react-toolbox/react-toolbox-example#28]
Following the exact same instructions of the README:

> `Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module '~normalize.css'`

![image](https://cloud.githubusercontent.com/assets/7553006/17944765/77db610a-6a17-11e6-9e76-9c47e9a42ac0.png)

It happens when navigating to `http://0.0.0.0:8080/` and a blank page is displayed.

Small workaround to "make it work":

![image](https://cloud.githubusercontent.com/assets/7553006/17945295/9b5b6da8-6a19-11e6-9804-6a54f4156f7b.png)

Node v4.5.0

**Comment by ludoo0d0a** [comment]
or add the missing dependency

`npm install normalize.css --save`

**Comment by ChitaGideon** [comment]
I got same exception 
`npm install normalize.css --save`  do not really solve my problem

**Comment by huysamen** [comment]
+1 same problem.  Also still persists after installing normalize.css

**Comment by huysamen** [comment]
Actually, this fixed it for me:

```
rm -rf node_modules
npm cache clean
npm install
```

**Comment by johanarnor** [comment]
Same problem here, cleaning the npm cache didn't fix it.
node v6.2.0, npm v3.8.9

**Comment by javivelasco** [comment]
Maybe it's related to the configuration? I'll look into it but with the next react-toolbox version we are getting rid of these imports :)

**Comment by erkurita** [comment]
Can confirm. Fresh checkout, same issue:

```
$ npm --version
2.11.3
$ nodejs --version
v4.5.0
```

**Comment by douglasjunior** [comment]
I just updated my dependencies using npm-check-updates and works.

![captura de tela 2016-08-30 as 13 40 15](https://cloud.githubusercontent.com/assets/1512341/18098263/d5c79d0c-6eb7-11e6-949d-98963dec397a.png)

``` bash
$ npm --version
3.10.5
$ node --version
v6.2.2
```
