### ISSUE TITLE
Webpack babel experimental class support

### ISSUE THREAD

**Issue by mauron85** [react-toolbox/react-toolbox-example#3]
Webpack throws following error on React Component:

```
Module build failed: SyntaxError: components/dialog/index.jsx: Unexpected token (20:15)
  18 |   }
  19 |
> 20 |   closeDialog = () => {
     |                ^
  21 |     this.refs.dialog.hide();
  22 |   };
  23 |
```

And this is the class, basically any class using babel experimental class support,

```
class DialogTest extends React.Component {
  showDialog = () => {
    this.refs.dialog.show();
  };

  closeDialog = () => {
    this.refs.dialog.hide();
  };

  actions = [
    { label: "Cancel", onClick: this.closeDialog },
    { label: "Save", onClick: this.closeDialog }
  ];

  render () {
    return (
      <div>
        <Button label='Show my dialog' onClick={this.showDialog} />
        <Dialog ref='dialog' title='My awesome dialog' type='small' actions={this.actions}>
          <p>Here you can add arbitrary content. Components like Pickers are using dialogs now.</p>
        </Dialog>
      </div>
    );
  }
}

return <DialogTest />;
```

I don't know how to enable babel exp. features with webpack 5.x.

**Comment by javivelasco** [comment]
The example is not complete. It should be getting components from `lib` instead of `components` so you don't need to include the module in your JSX. There is no reason for that. Anyway, if you get the components from the ES6 source you should add to babel configuration class initializers (`es7.classProperties`).

In a couple of hours I cant take a look on it and update the example. Hold on

**Comment by mauron85** [comment]
Ok. NP. 
Just to make thing clear. It's not react-toolbox component that is causing problem, but my own. React-toolbox components are fine. I just used example http://react-toolbox.com/#/components/dialog as reference in my first comment.

**Comment by javivelasco** [comment]
Ah! Ok so what it's missing is probably the babel configuration. To add property initializers add the option in your babel configuration in webpack. Also you can better use `babelrc` file. Check Toolbox main repo

**Comment by mauron85** [comment]
Ok. Already resolved, thanks to your lead (es7.classProperties).

webpack.config.file.js

```
...
  module: {
    loaders: [
      {
        test: /(\.js|\.jsx)$/,
        // exclude: /(node_modules)/,
        loader: 'babel',
        query: {
          optional: ["es7.decorators", "es7.classProperties"]
        }        
      }, {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap')
      }
    ]
  },
...
```

**Comment by javivelasco** [comment]
Nice! Another option is to configure babel from `babelrc`. That would allow you to share options across different configuration files in your project as it happens in Toolbox + Docs.
