### ISSUE TITLE
Webpack2 support

### ISSUE THREAD

**Issue by jihocech** [react-toolbox/react-toolbox-example#32]
Would be nice to have an example with the Webpack 2 setup.

**Comment by javivelasco** [comment]
I'm updating during this week the repository to set an example with react toolbox 2 beta. I'll do it with webpack 2 :)

**Comment by janusch** [comment]
That would be fantastic @javivelasco I am somehow struggeling. React-toolbox is awesome though!

**Comment by janusch** [comment]
It actually just works&#8482; using react-toolbox@2

In webpack.config.js something like this and one is good to go:

```
const cssModuleLoaders = [
  'css?sourceMap&modules&importLoaders=2&localIdentName=[name]__[local]___[hash:base64:5]',
  'postcss',
  'sass?sourceMap&sourceMapContents&outputStyle=expanded',
];

module: {
          loaders: [
              {
                  test: /\.js$/,
                  loaders: ['babel'],
                  include: [/scripts/,
                   /node_modules\/react-toolbox/,]
              }, {
                test: /(\.scss|\.css)$/,
                include: [
                  /node_modules\/react-toolbox/,
                ],
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style',
                    loader: cssModuleLoaders,
                }),
              }
     ]
}
```

I havn't tried to do my own theme yet though. I hope that this works just as well.
One little issue still remains that is webpack having an issue with generating the sourcemaps for e.g. identifiers.js when  `UglifyJsPlugin({
            sourceMap: true,
            minimize: true
          })` is active.

Maybe more of a webpack issue than react-toolbox.

Thanks for the great work making react-toolbox webpack 2 compatible!

**Comment by janusch** [comment]
Uhm, I was a bit too optimistic yesterday. In my case it works in chrome because chrome supports css var(). In other browsers there are issues. So apparently css-next does not do its job right in transforming the vars into valid css :(

Also i am still using the sass-loader as you can see above, that way I get at least all the files.

This whole css-post-pre-next thing is a bit over my head. Yeah, css was sometimes messy, but it would just work without too much overhead or a long tool chain (order matters).

Does anyone have a working webpack 2 config for react-toolbox@2.beta?

**Comment by javivelasco** [comment]
I have it locally configured but it's not pushed yet because there are build changes I need to make. I'm trying to do it asap. Check the way webpack 2 is configured with postcss. The options are passed differently now. You should give for now the same configuration used in the docs because there is no preprocessing yet at all!

**Comment by janusch** [comment]
Thanks for the reply @javivelasco !
Which configuration used in the docs are you thinking of? I cannot find a working config, not sure where to look?
For now I might have to revert back to webpack1 and react-toolbox1 to get something working again. 
I am still stuck with the same issue that cssnext does not transpile the variables.

Thanks for your help!

**Comment by javivelasco** [comment]
No problem. In the css-next branch of react-toolbox there is a webpack configuration. Also, in the same branch there is a consumer config for the docs subproject. You can check one of those for a working example of the current beta release. I'll try to keep digging on the build system and a new example branch in this repository during the weekend

**Comment by janusch** [comment]
Thank you @javivelasco for the reply!
I had a quick look at the webpack.configs you pointed me to. I think my problem is translating this to webpack 2, and to get cssnext to transpile the css to something that is understood by most browsers.

Would still be fantastic if you could set up a simple webpack 2 react-toolbox@2 example where the css works. I am most likely only going to use cssnext and other postcss plugins to build react-toolbox's css, for my custom css I am using scss and do not see a problem for it.

Why did you decide to switch to cssnext instead of the current setup in react-toolbox@1?
I still have a hard time seeing the benefits and do not like that it adds so much complexity for the tool chain for just styling some components?

**Comment by janusch** [comment]
Hey @javivelasco,
did you have the time to get a working webpack@2 & react-toolbox@2 example up and running.
I gathered courage over the weekend and tried again today and got some different errors:
I had a close look at the webpack.configs of the cssnext branch without success. One reason is that webpack is still v1 in that branch and the way to configure loaders has changed a bit.

e.g.: 

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/react-toolbox/lib/button/theme.css
    Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird
```

Have you seen this error before?

After removing all the composes from the theme.css webpack does actually do its job. Now I am just back at where cssnext somehow has not doe its job and transformed css variables and `:root` element into valid css.

Any pointers into the right direction are greatly appreciated.

Also, do you describe your choice for going with this css toolchain somewhere? For me it is difficult to understand why react-toolbox is moving away from scss and betting onto cssnext which arguably adds a lot of overhead on the configuration side of things?

Cheers

**Comment by javivelasco** [comment]
Hi! @janusch sorry for my late answer. I have an example running locally with CSS Modules but not with react-toolbox. Did you get it working?

**Comment by InSuperposition** [comment]
I was able to get react-toolbox working using webpack 2's `LoaderOptionsPlugin`

```javascript
new webpack.LoaderOptionsPlugin({
      options: {
        // for resolve-url-loader
        // context and output options must be set
        context: path.resolve(__dirname),
        output: {
          path: path.resolve(__dirname, 'www'),
        },
        // for react-toolbox
        sassLoader: {
          data: '@import \'theme.scss\';',
          includePaths: [path.resolve(__dirname, 'src/assets/themes')],
        },
        // other loader options
        postcss: [autoprefixer],
      },
    }),
```

**Comment by jcmcneal** [comment]
I struggled with this for a few hours and this is what finally got it working for me using webpack@beta, extract-text-webpack-plugin@beta, css-loader, and sass-loader. (I removed settings not related to CSS/SASS).

```
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const cssModuleLoaders = [
  'css-loader?sourceMap&modules&importLoaders=2&localIdentName=[name]__[local]___[hash:base64:5]',
  'sass-loader?sourceMap&sourceMapContents&outputStyle=expanded',
];

module: {
      loaders: [
        {
          test: /(\.scss|\.css)$/,
          include: [
            /node_modules\/react-toolbox/,
          ],
          loader: ExtractTextPlugin.extract({
              fallbackLoader: 'style-loader',
              loader: cssModuleLoaders,
          })
        }
      ]
    },
plugins: [
        new ExtractTextPlugin("[name].css"),
    ],
```

It kept throwing errors on `react-toolbox/.../theme.css` and like the documentation says it needs a SASS loader. These stylesheets get loaded into the JavaScript files and `ExtractTextPlugin` pulls it out, formats it to proper CSS syntax, and dumps it wherever you specify in `new ExtractTextPlugin("[name].css")`. I was getting the `".raised" is weird` error too because I wasn't using the `ExtractTextPlugin`. Hopefully this helps someone.

**Comment by mcarlotta** [comment]
@jcmcneal Thanks! Was getting the same error about the ".raised" is weird. Now running into 'Error in ./~/react-toolbox/lib/button/index.js Module not found: '[object Object]' Anyone else having same issue? Inside component 'import { Button } from 'react-toolbox/lib/button';

**Comment by jcmcneal** [comment]
@mcarlotta I was getting the same error. Do you mind posting your config file? Also, what versions of webpack/extract-text-webpack-plugin are you using?

**Comment by mcarlotta** [comment]
This config seemed to fix the issue:

     {
        test: /(\.scss|\.css)$/,
        loaders: [
          require.resolve('style-loader'),
          require.resolve('css-loader') + '?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
          require.resolve('sass-loader') + '?sourceMap'
        ]
      },

**Comment by jcmcneal** [comment]
@mcarlotta Nice! That is a much simpler solution. It worked flawlessly for me and I like that it doesn't generate a separate stylesheet!

**Comment by mcarlotta** [comment]
Credit goes here: https://github.com/react-toolbox/react-toolbox/issues/93

**Comment by janusch** [comment]
Yea, this is a nice and simple solution! Thank you!

> I'm updating during this week the repository to set an example with react toolbox 2 beta. I'll do it with webpack 2 :)

Would be very nice to have an example with this too. I got it with SCSS to work now, but with postcss i have totally given up for now, sorry.

**Comment by plnt9machine** [comment]
I've used the setup from here and the style gets loaded but i get some weird styling issues, it seems that the css modules don't work correctly so there is an issue with some style conflicts. In my case the icons get global style and all of the icons have a right margin

**Comment by olegstepura** [comment]
Seems like the examples above are using webpack 1.x configuration syntax.

I was able to use `react-toolbox@2.0.0-beta.4` with `webpack@2.2.0-rc.6` and `react-hot-loader@3.0.0-beta.6` using this config:
<details><summary>webpack.config.js</summary>

```js
const path = require('path');
const webpack = require('webpack');

const settings = {
  entry: {
    backend: [
      "react-hot-loader/patch",
      "./src/main/frontend/index.jsx"
    ]
  },
  output: {
    filename: "[name].js",
    publicPath: "/asset/",
    path: path.resolve("src/main/webapp/asset")
  },
  resolve: {
    extensions: [".js", ".jsx", ".json"]
  },
  devtool: "eval-source-map",
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader'
      },
      {
        test: /\.css$/,
        use: [
          "style-loader",
          {
            loader: "css-loader",
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1
            }
          },
          "postcss-loader" // has separate config nearby
        ]
      },
    ]
  },
  devServer: {
    contentBase: path.resolve("src/main/webapp"),
    publicPath: "http://localhost:8080/asset/", // full URL is necessary for Hot Module Replacement.
    quiet: false,
    hot: true,
    historyApiFallback: true,
    inline: true
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new webpack.LoaderOptionsPlugin({
      debug: true
    }),
  ],
};

module.exports = settings;
```
</details>

<details><summary>postcss.config.js</summary>

```js
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions', '> 5%'],
    },
  },
};
```
</details>

**Comment by javivelasco** [comment]
thanks @olegstepura! We should update the repository to use webpack 2. Do you want to submit a pr??

**Comment by olegstepura** [comment]
@javivelasco here it is https://github.com/react-toolbox/react-toolbox-example/pull/41

**Comment by javivelasco** [comment]
Cool! Thank you @olegstepura

**Comment by Un3qual** [comment]
@mcarlotta When I use your solution after using `yarn add sass-loader` and `yarn add node-sass` i get

```
ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/sass-loader/lib/loader.js?sourceMap!./~/style-loader!./~/css-loader!./~/sanitize.css/sanitize.css
Module build failed: 
/*! sanitize.css v4.1.0 | CC0 License | github.com/jonathantneal/sanitize.css */
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in /Users/admin/Desktop/Programming/Forum/frontend-tests/react-boilerplate/node_modules/sanitize.css/sanitize.css (line 1, column 1)
 @ ./~/sanitize.css/sanitize.css 4:14-242 13:2-17:4 14:20-248
 @ ./app/app.js
 @ multi main
```
I'm using `react-boilerplate`

**Comment by etienne-bondot** [comment]
Thanks @olegstepura. After struggling for hours with this, it's finally working has expected with your solution.

**Comment by javivelasco** [comment]
Now its merged!
