### ISSUE TITLE
Webpack resolve modules question

### ISSUE THREAD

**Issue by dcworldwide** [react-toolbox/react-toolbox-example#33]
When using the ExtractTextPlugin plugin to resolve all styles, won't this load stylesheets from other node module folders that are not part of react-toolbox and should thus be ignored?

```
extensions: ['', '.js', '.jsx', '.scss'], 
        modulesDirectories: [
            'node_modules',
            path.resolve(__dirname, './node_modules')
        ]
```

**Comment by javivelasco** [comment]
Depends on how do you configure and require of course. That example is probably not the best though because we need to tweak a bit the configuration to use the upper directory as if it were the final build. Anyway, you only bundle what you require so I guess you just need to be careful!

**Comment by javivelasco** [comment]
Wow I thought this was react-toolbox main repository, it's not the best configuration example anyway, I should change it
