### ISSUE TITLE
Ripple tag won't be removed 

### ISSUE THREAD

**Issue by ashleyyang0610** [react-toolbox/react-toolbox-example#36]
The ripple tag won't be removed after clicking button.
I found that the ripple tag won't be removed in my project.
But it can't be reproduced on [react-toolbox web page](http://react-toolbox.com/#/components/button) example.
So I try it on react-toolbox-example, and it happens.
As below snapshot, I click the SuccessButton in react-toolbox-example.`<span data-react-toolbox="ripple" class="theme__rippleWrapper___2AWhQ theme__rippleWrapper___2zthi"></span>` tag should be removed but it won't.
<img width="875" alt="2016-10-25 7 02 36" src="https://cloud.githubusercontent.com/assets/22339489/19683652/a4f7cd96-9ae5-11e6-8366-6187dc9aaae9.png">

**Comment by ashleyyang0610** [comment]
@javivelasco Hi javi~ May I know there's any command or suggestion for it?

**Comment by javivelasco** [comment]
Sorry @ashleyyang0610 This is probably happening because it's a bug in react-toolbox. It was already fixed so it should work!
