### ISSUE TITLE
Cannot resolve module 'style'

### ISSUE THREAD

**Issue by m19c** [react-toolbox/react-toolbox-example#7]
Hmmmm... I am using _webpack_ for two different sections (based on the configuration of this repository) of my application (main and admin). The endpoint admin wont start because each `react-toolbox` component (e.g. face as showed below).

```
ERROR in ./~/react-toolbox/lib/time_picker/clock/face.js
Module not found: Error: Cannot resolve module 'style' in /PATH/TO/MY/PROJECT/node_modules/react-toolbox/lib/time_picker/clock
 @ ./~/react-toolbox/lib/time_picker/clock/face.js 29:13-31
```

The configuration looks like this:

```
// core/webpack/config.js
var path = require('path');
var webpack = require('webpack');
var autoprefixer = require('autoprefixer');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = function generateConfig(endpoint) {
    var dirname = `${process.cwd()}/core/resource/app/${endpoint}`;

    return {
        context: dirname,
        devtool: 'inline-source-map',
        entry: [
            'webpack-hot-middleware/client',
            path.join(dirname, 'src', 'bootstrap')
        ],
        output: {
            path: path.join(dirname, '../../static/app'),
            filename: `${endpoint}.js`,
            publicPath: '/app'
        },
        plugins: [
            new webpack.HotModuleReplacementPlugin(),
            new webpack.NoErrorsPlugin(),
            new ExtractTextPlugin('react-toolbox.css', { allChunks: true })
        ],
        module: {
            loaders: [
                {
                    test: /(\.js|\.jsx)$/,
                    exclude: /(node_modules)/,
                    loader: 'babel'
                },
                {
            test: /(\.scss|\.css)$/,
            loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap!toolbox')
          }
            ]
        },
        resolve: {
            extensions: ['', '.jsx', '.scss', '.js', '.json'],
            modulesDirectories: [
                'node_modules',
                `${process.cwd()}/node_modules`
            ]
        },
        postcss: [autoprefixer]
    };
};

// core/resource/app/main/config.js
var webpack = require('../../../webpack/config');

module.exports = webpack('admin');
```

Any idea?

**Comment by javivelasco** [comment]
I can't see anything weird right now to stop toolbox working. Maybe you can give me a repository or some way of access to your project to check the whole thing and help you?

**Comment by m19c** [comment]
Added you as a collaborator to the project. I drop you a mail with instructions.

**Comment by developit** [comment]
@MrBoolean I got this error too when setting things up. It was due to one of the webpack loaders being missing/unbuilt.  I just ran this to ensure I had everything from the scss pipeline:

``` sh
npm i -D extract-text-webpack-plugin style-loader css-loader postcss-loader sass-loader toolbox-loader
```

The message from Webpack is confusing, but you'll see that if you comment out or remove the `scss` loader from your webpack config, the `.scss` files get reported as being invalid JavaScript, so they are being included.

**Comment by javivelasco** [comment]
Thanks @developit ! I didn't have time enough to check the project @MrBoolean. Can you try what he said? :smile:

**Comment by m19c** [comment]
Great! Works for me!

**Comment by javivelasco** [comment]
Awesome!

**Comment by fgarcia** [comment]
I've just noticed several issues quoting the same error message. Is there any reason for scss files to be required without extension?

The only implicit extensions I use are 'js' and 'jsx' and although having css extensions being automatically recognized is a matter of taste, maybe having the 'scss' extension explicitly written would make better error codes.

**Comment by javivelasco** [comment]
There is not a specific reason why we are avoiding extensions. I should work so maybe we can add them if we are getting better error codes. Not a big deal. Maybe you can open an issue?

**Comment by steviesama** [comment]
I'm getting the following...no idea off-hand what's going on. Was having "...cannot find module style...", then sass, and stuff like that so I sequentially npm installed those, now I'm getting this:

(you may have to copy and paste this screen shot as clicking from github seems to give a 404)
[http://i.imgur.com/59e27yo.png](url)
