### ISSUE TITLE
TypeError: Cannot read property 'flat' of undefined

### ISSUE THREAD

**Issue by CalebEverett** [react-toolbox/react-toolbox-example#8]
HI, looking forward to using what looks like a terrific set of components. I've been trying to get them installed in [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) and am almost all the way there. I've got the webpack config set up and it's building all the way through with no errors, but when I view the site at local host, I'm getting this error:

```
TypeError: Cannot read property 'flat' of undefined
Button.render
D:\projects\rrum\node_modules\react-toolbox\lib\button\index.js:65:41
```

Any ideas on what might be causing this?

**Comment by javivelasco** [comment]
Hi! Maybe you can paste some of the source code that's generating the error? Apparently there is nothing to generate that error en the source code of button component. Either the ES6 nor the compiled source...

**Comment by javivelasco** [comment]
Still happening?

**Comment by CalebEverett** [comment]
Yes, thanks for checking back - still happening, but I'm pretty sure this has to do with my not having it set up correctly. You can go ahead and close. If I get something going that would be useful to others I'll revert back. Thanks,

**Comment by javivelasco** [comment]
Nice, closing then. Anyway we have a reference here so we can reopen if something else happens.
Thanks @CalebEverett !
